image: node:alpine

cache:
  paths:
  - node_modules/

variables:
  DOCKER_REGISTRY: "registry.gitlab.com/danila/"

stages:
 - build
 - push
 - release

compile:
  stage: build
  tags:
    - docker
  script:
    - npm i
    - npx tsc

build_image:
  image: docker:latest
  before_script:
      - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY
  services:
  - docker:dind
  stage: build
  script:
    - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com
    - docker build -t registry.gitlab.com/danila/test2-docker .
    - docker push registry.gitlab.com/danila/test2-docker:latest
    